# H2 In-Memory database for local development
spring.datasource.url=jdbc:h2:mem:smartground;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.liquibase.enabled=false

# H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# External Mosquitto broker config
mqtt.broker.url=tcp://localhost:1883
mqtt.clientId=smartground-local
mqtt.topic.discovery=devices/discovery

logging.level.ch.jp.shooting=DEBUG
