server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smartground
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.liquibase.enabled=false

mqtt.broker.url=tcp://localhost:1883
mqtt.clientId=smartground-dev

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
