package ch.jp.shooting.node.box;

import ch.jp.shooting.node.onboarding.ProvisioningTokenService;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.MediaType;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.test.web.servlet.client.RestTestClient;

import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;

/**
 * Deviation from the task-8 brief's exact test code, per the coordinator's known-issue note:
 * {@code org.springframework.boot.test.web.client.TestRestTemplate} (and its
 * {@code HttpClientOption.SSL}, used by the brief to auto-trust the self-signed dev cert) is
 * absent from the cached {@code spring-boot-test-4.0.5.jar} in this offline sandbox (confirmed
 * in task 7 — no {@code org/springframework/boot/test/web/client/} package at all in that jar),
 * and there is no network access to fetch a complete one. This uses
 * {@code org.springframework.test.web.servlet.client.RestTestClient.bindToServer(...)} instead
 * (present in the already-cached {@code spring-test-7.0.6.jar}, proven working for a real
 * embedded-server request in task 7's {@code BoxStatusControllerTest}), backed by a
 * {@link SimpleClientHttpRequestFactory} whose JVM-wide default SSL trust is relaxed to accept
 * any certificate. That relaxed trust is installed once for the whole JVM via
 * {@link HttpsURLConnection#setDefaultSSLSocketFactory} / {@code setDefaultHostnameVerifier} —
 * acceptable only because this is a dev-only smoke test against a known self-signed cert
 * (Subject {@code CN=smartground-node}) generated by this same module's build; this pattern
 * must never be used in production code.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class BoxApiHttpsTest {

    @LocalServerPort
    private int port;

    @Autowired
    private ProvisioningTokenService tokenService;

    @BeforeAll
    static void trustSelfSignedDevCertificateJvmWide() throws Exception {
        TrustManager[] trustAllCerts = new TrustManager[] {
                new X509TrustManager() {
                    @Override
                    public void checkClientTrusted(X509Certificate[] chain, String authType) {
                    }

                    @Override
                    public void checkServerTrusted(X509Certificate[] chain, String authType) {
                    }

                    @Override
                    public X509Certificate[] getAcceptedIssuers() {
                        return new X509Certificate[0];
                    }
                }
        };
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, trustAllCerts, new SecureRandom());
        HttpsURLConnection.setDefaultSSLSocketFactory(sslContext.getSocketFactory());
        HttpsURLConnection.setDefaultHostnameVerifier((hostname, session) -> true);
    }

    @Test
    void discoveryEndpoint_isReachableOverHttps() {
        RestTestClient client = RestTestClient.bindToServer(new SimpleClientHttpRequestFactory())
                .baseUrl("https://localhost:" + port)
                .build();

        // Discovery is token-gated (box-api, Task 7): mint a one-time provisioning token for this
        // MAC first, same as BoxDiscoveryControllerTest, so this smoke test still exercises a real
        // 2xx response instead of the now-expected 400 /errors/invalid-provisioning-token.
        String token = tokenService.mint("AA:BB:CC:DD:EE:30").hex();

        client.post()
                .uri("/box-api/v1/discovery")
                .contentType(MediaType.APPLICATION_JSON)
                .body("""
                    {"macAddress":"AA:BB:CC:DD:EE:30","token":"%s","appVersion":"1.0.0",
                    "firmwareVersion":"micropython-1.23","boxType":"thrower","capabilitiesJson":"{}"}
                    """.formatted(token))
                .exchange()
                .expectStatus().is2xxSuccessful();
    }
}
