package ch.jp.shooting.node.box;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.MediaType;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.client.RestTestClient;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;

import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;
import java.time.Instant;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Deviation from the task-7 brief's exact test code, documented in task-7-report.md: the
 * offline environment's cached {@code spring-boot-test-autoconfigure} jar is missing the
 * {@code web/servlet} package (no {@code @AutoConfigureMockMvc}), and there is no network
 * access to fetch a complete one. Per coordinator instruction, this uses
 * {@code MockMvcBuilders.standaloneSetup(...)}, mirroring
 * {@code BoxDiscoveryControllerTest} in this same package, while still loading a real
 * {@code BoxRecordRepository} bean via {@code @SpringBootTest} so the test exercises the
 * real JPA path end-to-end rather than mocks. {@code @Transactional} mirrors
 * {@code BoxDiscoveryControllerTest}/{@code BoxProvisioningServiceTest}/
 * {@code BoxRecordRepositoryTest} in this same package, which roll back against the
 * file-based H2 datasource for the same reason — no in-memory test datasource is
 * configured for this module.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Transactional
class BoxStatusControllerTest {

    @Autowired
    private BoxRecordRepository repository;

    @LocalServerPort
    private int port;

    private MockMvc mockMvc;

    /**
     * Since task 8 (HTTPS with a self-signed dev certificate), the embedded server used by the
     * real-embedded-server test below only accepts TLS connections. This relaxes the JVM-wide
     * default SSL trust to accept any certificate, matching the pattern proven in
     * {@code BoxApiHttpsTest} in this same package — acceptable only because this is a dev-only
     * test against a known self-signed cert generated by this module's own build.
     */
    @BeforeAll
    static void trustSelfSignedDevCertificateJvmWide() throws Exception {
        TrustManager[] trustAllCerts = new TrustManager[] {
                new X509TrustManager() {
                    @Override
                    public void checkClientTrusted(X509Certificate[] chain, String authType) {
                    }

                    @Override
                    public void checkServerTrusted(X509Certificate[] chain, String authType) {
                    }

                    @Override
                    public X509Certificate[] getAcceptedIssuers() {
                        return new X509Certificate[0];
                    }
                }
        };
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, trustAllCerts, new SecureRandom());
        HttpsURLConnection.setDefaultSSLSocketFactory(sslContext.getSocketFactory());
        HttpsURLConnection.setDefaultHostnameVerifier((hostname, session) -> true);
    }

    @BeforeEach
    void seedKnownBox() {
        // Defensively clear this test's fixture MAC within the (rolled-back) test transaction:
        // this module's H2 datasource is file-based, not in-memory, so a MAC committed by an
        // earlier, non-transactional run against this same local dev file would otherwise leak
        // across runs. The delete itself is rolled back with everything else in this test.
        repository.findByMacAddress("AA:BB:CC:DD:EE:20").ifPresent(repository::delete);

        BoxRecord record = new BoxRecord();
        record.setMacAddress("AA:BB:CC:DD:EE:20");
        record.setKBox(new byte[32]);
        record.setProvisionedAt(Instant.now());
        repository.save(record);

        mockMvc = MockMvcBuilders.standaloneSetup(new BoxStatusController(repository))
                .setControllerAdvice(new ProblemDetailAdvice())
                .build();
    }

    /**
     * The app-level fix ({@code spring.mvc.problemdetails.enabled=true} in
     * {@code application.properties}) is what makes the deployed app render
     * {@link ch.jp.shooting.node.hub.ErrorResponseException}-style ProblemDetail bodies as
     * real {@code application/problem+json} responses. It only takes effect through Boot's
     * autoconfigured {@code DefaultErrorAttributes}/{@code ResponseEntityExceptionHandler}
     * wiring, which {@link MockMvcBuilders#standaloneSetup} deliberately bypasses (it builds a
     * bare {@code DispatcherServlet} with no Boot autoconfiguration at all). This advice is
     * therefore still required for this standalone test to render a body — but it now exists
     * purely to reproduce, inside the test harness, the same rendering behavior the property
     * already provides in the real, Boot-autoconfigured application; it is no longer a
     * substitute for that behavior. A genuine end-to-end test against a real embedded server
     * was attempted via {@code TestRestTemplate} first, but that class is absent from the
     * cached {@code spring-boot-test-4.0.5.jar} in this offline environment (no network
     * access to fetch a complete one — the same constraint noted on this class regarding
     * {@code @AutoConfigureMockMvc}). {@code status_unknownBox_realEmbeddedServer_rendersProblemDetail404()}
     * below provides that genuine end-to-end proof instead, using
     * {@code org.springframework.test.web.servlet.client.RestTestClient} (in
     * {@code spring-test-7.0.6.jar}, a transitive dependency here), backed by the synchronous
     * {@code RestClient} from {@code spring-web} — no {@code TestRestTemplate} or
     * WebFlux/Reactor required.
     */
    @ControllerAdvice
    static class ProblemDetailAdvice extends ResponseEntityExceptionHandler {
    }

    @Test
    void status_knownBox_returns200AndUpdatesLastSeen() throws Exception {
        mockMvc.perform(post("/box-api/v1/boxes/{mac}/status", "AA:BB:CC:DD:EE:20")
                .contentType("application/json")
                .content("""
                    {"status":"idle"}
                    """))
            .andExpect(status().isOk());

        var updated = repository.findByMacAddress("AA:BB:CC:DD:EE:20").orElseThrow();
        org.assertj.core.api.Assertions.assertThat(updated.getLastStatus()).isEqualTo("idle");
        org.assertj.core.api.Assertions.assertThat(updated.getLastSeenAt()).isNotNull();
    }

    @Test
    void status_unknownBox_returns404() throws Exception {
        mockMvc.perform(post("/box-api/v1/boxes/{mac}/status", "00:00:00:00:00:99")
                .contentType("application/json")
                .content("""
                    {"status":"idle"}
                    """))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.type").value("/errors/box-unknown"));
    }

    /**
     * Genuine end-to-end proof, requested in review: a real HTTP request against the real
     * embedded Tomcat instance ({@code webEnvironment = RANDOM_PORT} + {@code @LocalServerPort}),
     * going through Boot's actual autoconfiguration (the {@code spring.mvc.problemdetails.enabled=true}
     * property in {@code application.properties}) instead of the {@code ProblemDetailAdvice}
     * test double declared above, which only exists to reproduce that behavior for the
     * {@code standaloneSetup} tests in this class. {@code TestRestTemplate} is unavailable in
     * this offline sandbox (see the class javadoc), so this uses {@code RestTestClient.bindToServer()},
     * backed by the synchronous {@code RestClient} from {@code spring-web}, which is on the
     * classpath here.
     *
     * <p>No seed data is needed — the case under test is an unknown MAC — so the outer
     * {@code @Transactional} rollback (which would not apply to the embedded server's own
     * connection/thread anyway) is irrelevant here. The MAC below is scoped to this test only
     * and distinct from every other fixture MAC in this package, so it is guaranteed absent
     * from the file-based H2 database regardless of run order.
     */
    @Test
    void status_unknownBox_realEmbeddedServer_rendersProblemDetail404() {
        RestTestClient client = RestTestClient.bindToServer(new SimpleClientHttpRequestFactory())
                .baseUrl("https://localhost:" + port)
                .build();

        client.post()
                .uri("/box-api/v1/boxes/{mac}/status", "E2:E2:00:00:00:01")
                .contentType(MediaType.APPLICATION_JSON)
                .body("""
                    {"status":"idle"}
                    """)
                .exchange()
                .expectStatus().isNotFound()
                .expectBody()
                .jsonPath("$.type").isEqualTo("/errors/box-unknown");
    }
}
